### ISSUE TITLE
why cannot compile

### ISSUE THREAD

**Issue by shuangwen-thu** [Jinwen-XU/jwjournal#1]
Hi, author. I cannot compile your file using pdflatex or xelatex under texlive 2021.
Is there something wrong, or I must have missed it.
Could you please give me some help?

**Comment by shuangwen-thu** [comment]
I successfully compile the file under texlive 2022.
However, it took so much time, even unacceptable!!!

**Comment by Jinwen-XU** [comment]
If you are writing your document in Chinese, then it is preferable to install the following open-source fonts:

- The Source Han font series (思源字体) at [Adobe Fonts](https://github.com/adobe-fonts). More specifically:
  - Source Han Serif, [go to its Release page](https://github.com/adobe-fonts/source-han-serif/releases).
  - Source Han Sans, [go to its Release page](https://github.com/adobe-fonts/source-han-sans/releases).
  - Source Han Mono, [go to its Release page](https://github.com/adobe-fonts/source-han-mono/releases).
  > It is recommended to download the Super-OTC version, so that the total download size would be smaller, and the installation would be easier.

Without these fonts, the compilation would still passing, but the system shall spend (quite) some time verifying that the fonts are indeed missing and only then switch to the fallback fonts.

Feel free to continue the discussion here or open a new issue page if you encounter any further problem. Also, it is OK to write in Chinese if it is more convenient for you, I am certainly much more fluent with Chinese than English or French.
