### ISSUE TITLE
Compilation does not pass on overleaf, using texlive2022, pdflatex

### ISSUE THREAD

**Issue by sinopaul** [Jinwen-XU/jwjournal#2]
Compilation does not pass on overleaf, using texlive2022, pdflatex

**Comment by Jinwen-XU** [comment]
With the very few information you provided I cannot really help much. It would be helpful to know, for example:

- Which document are you currently compiling? Is it one of the demo documents or your own document?
  (More specifically, in which language are you writing your document? If it is, say, Chinese, then using format like XeLaTeX or LuaLaTeX would be necessary.)
- Which version of the package are you using?
- What is the error that prevents the compilation?

It would be nice if you can show the content of the `.log` file, in which one may find most of the things need to know.

**Comment by Jinwen-XU** [comment]
Since I am not getting any further information, I shall mark this issue as closed. If you encounter any further issue, please feel free to reopen it.
